/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author moeja
 */
public class UpdateCar extends javax.swing.JFrame {
Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
  
    /**
     * Creates new form UpdateCar
     */
    public UpdateCar() {
        initComponents();
         con=DBConnection.ConnectionDB();
           UpdateTable();
           updatecombo();
        //  updatecombo2();
       
          /*    try{
               String sql = "SELECT * from Car; ";
               pst = con.prepareStatement(sql);
               rs = pst.executeQuery();
               DefaultTableModel model = (DefaultTableModel)table3.getModel();
               model.setRowCount(0);
               while(rs.next()){
                   model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9)});
               }
               
    }                                        
catch(Exception e){
    System.out.println("Error" + e);
}
           */
    }
    private void UpdateTable(){
        String sql = "select * from Car3;";
        try {
            pst = con.prepareStatement(sql);
            rs= pst.executeQuery();
         table3.setModel(DbUtils.resultSetToTableModel(rs));
             
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
         finally{
            try{
            rs.close();
            pst.close();
            
        }
            catch(Exception e){
                
            }
        }
    }
    private void updatecombo(){
        String sql = "select * from Car3";
        try {
            pst = con.prepareStatement(sql);
            rs=pst.executeQuery();
            while(rs.next()){
                JJ.addItem(rs.getString("ID"));
            }
        } catch (Exception e) {
        }
        
    }
    private void updatecombo2(){
        String sql = "select * from Car3";
        try {
            pst = con.prepareStatement(sql);
            rs=pst.executeQuery();
            while(rs.next()){
                MM.addItem(rs.getString("Availability"));
            }
        } catch (Exception e) {
        }
        
    }
    /* 
    //////
     String sql = "update Car set "
               + " Type = '" + Type.getText() + "',"
               + " Brand = '" +Brand.getText() + "',"+ 
                 " Model = '" +Model.getText() + "',"+
               " Color = '" +Color.getText() + "',"+
                 " LicensePlate = '" +LicensePlate.getText() + "'" +
             "where Availability = " +MM.getSelectedItem().toString() + "',"+
                " HourlyRate = '" +HourlyRate.getText() + "',"+
               " CustomerRenter = '" +Customer.getText() +  "'" +
               
              "where ID = " +JJ.getSelectedItem().toString(); //+ "'" + "where Availability = " +MM.getSelectedItem().toString(); 
                       try {
            pst = con.prepareStatement(sql);
            pst.execute();
            UpdateTable();
            JOptionPane.showMessageDialog(null, "Record Updated successfully");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    
  
    
//////////
   
    


    
    
    
    */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        update = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        LicensePlate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        HourlyRate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Customer = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Type = new javax.swing.JTextField();
        Brand = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Model = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Color = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table3 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        JJ = new javax.swing.JComboBox<>();
        MM = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        ManuYear = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        AddCar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        IDCar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        jLabel4.setText("Model:");

        jLabel5.setText("Color:");

        jLabel6.setText("License Plate#: ");

        jLabel7.setText("Availability:");

        jLabel8.setText("Hourly Rate:");

        jLabel9.setText("Customer: ");

        Type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeActionPerformed(evt);
            }
        });

        jLabel2.setText("Type:");

        jLabel3.setText("Brand:");

        jButton1.setText("<------");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        table3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Car ID", "Type", "Brand", "Model", "Color", "License Plate", "Availability", "Hour Rate", "Customer "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table3MouseClicked(evt);
            }
        });
        table3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                table3KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(table3);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText(" Car Info Managament");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        JJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JJActionPerformed(evt);
            }
        });

        MM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Not Available" }));

        jLabel10.setText("Manufacture Year:");

        ManuYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManuYearActionPerformed(evt);
            }
        });

        jButton2.setText("Delete Car");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        AddCar.setText("Add Car");
        AddCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCarActionPerformed(evt);
            }
        });

        jLabel11.setText("ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel4)
                        .addGap(310, 310, 310))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(39, 39, 39)
                                    .addComponent(jLabel5))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(31, 31, 31)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel8))
                                        .addComponent(jLabel7))))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Customer, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(HourlyRate, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(MM, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LicensePlate, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                                .addComponent(Color, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                                .addComponent(ManuYear, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                                .addComponent(Model, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                                .addComponent(Brand, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                                .addComponent(Type, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                                .addComponent(IDCar))
                            .addGap(41, 41, 41))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(147, 147, 147)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(AddCar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(304, 304, 304)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(157, 157, 157)
                        .addComponent(JJ, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButton1)
                        .addGap(18, 46, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(IDCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(JJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Brand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Model, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(ManuYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LicensePlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(MM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(HourlyRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(Customer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(update)
                    .addComponent(jButton2)
                    .addComponent(AddCar))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
       //String sql2 =  jj.getSelectedItem().toString();
          //"  Availability = '" +ava.getText() + "',"+
     try {
           
    String sql = "UPDATE Car3 SET "
               + "Type = ?, "
               + "Brand = ?, "
               + "Model = ?, " 
               + "ManufactureYear = ?,"
               + "Color = ?, "
               + "LicensePlate = ?, "
               + "Availability = ?, "
               + "HourlyRate = ?, "
               + "CustomerRenter = ? "
               + "WHERE ID = ? AND EXISTS (SELECT 1 FROM Customer4 WHERE Name = ?)";
    
    pst = con.prepareStatement(sql);
    pst.setString(1, Type.getText());
    pst.setString(2, Brand.getText());
    pst.setString(3, Model.getText());
     pst.setString(4, ManuYear.getText());
    pst.setString(5, Color.getText());
    pst.setString(6, LicensePlate.getText());
    pst.setString(7, MM.getSelectedItem().toString());
    pst.setString(8, HourlyRate.getText());
    pst.setString(9, Customer.getText());
    pst.setString(10, JJ.getSelectedItem().toString());
    pst.setString(11, Customer.getText());
    
    int rows=pst.executeUpdate();
    UpdateTable();
     if (rows > 0) {
            JOptionPane.showMessageDialog(null, "Car Updated successfully");

    } else {
        JOptionPane.showMessageDialog(null, "Error. Customer Does Not Exist");
    }
   
   
} catch (SQLException e) {
    JOptionPane.showMessageDialog(null, e.getMessage());
} 
       finally{
            try{
            rs.close();
            pst.close();
            
        }
            catch(Exception e){
                
            }
        }
       
    }//GEN-LAST:event_updateActionPerformed

    private void TypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TypeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
        this.dispose();
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void table3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table3MouseClicked
     int row = table3.getSelectedRow();
    //  String sql2 =  jj.getSelectedItem().toString();
     String selection = table3.getModel().getValueAt(row, 0).toString();
     String sql = "select * from Car3 where ID =?"; //+ selection;
       String selection2 = table3.getModel().getValueAt(row, 7).toString();
     String sql2 = "select * from Car3 where Availability =?";// + selection2;
        try {
            pst = con.prepareStatement(sql);
                pst.setString(1, selection);
            rs = pst.executeQuery();
            if(rs.next()){
                JJ.setSelectedItem(rs.getString("ID"));
                IDCar.setText(rs.getString("ID"));
                Type.setText(rs.getString("Type"));
                Brand.setText(rs.getString("Brand"));
                Model.setText(rs.getString("Model"));
                ManuYear.setText(rs.getString("ManufactureYear"));
                Color.setText(rs.getString("Color"));
                LicensePlate.setText(rs.getString("LicensePlate"));
           //  ava.setText(rs.getString("Availability"));
                MM.setSelectedItem(rs.getString("Availability"));;
                HourlyRate.setText(rs.getString("HourlyRate"));
                Customer.setText(rs.getString("CustomerRenter"));
               
             // JOptionPane.showMessageDialog(null, "Update Complete");
 }
            pst = con.prepareStatement(sql2);
    pst.setString(1, selection2);
    rs = pst.executeQuery();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
     
  // int row = table3.getSelectedRow();
/*String selection = table3.getModel().getValueAt(row, 0).toString();
String sql = "SELECT * FROM Car WHERE ID = ?";
try {
    pst = con.prepareStatement(sql);
    pst.setString(1, selection);
    rs = pst.executeQuery();
    if(rs.next()){
        JJ.setSelectedItem(rs.getString("ID"));
        Type.setText(rs.getString("Type"));
        Brand.setText(rs.getString("Brand"));
        Model.setText(rs.getString("Model"));
        Color.setText(rs.getString("Color"));
        LicensePlate.setText(rs.getString("LicensePlate"));

        // Set the selected item of the combo box based on the value from the result set
        String availability = rs.getString("Availability");
        if (availability != null) {
            jj.setSelectedItem(availability);
        }

        HourlyRate.setText(rs.getString("HourlyRate"));
        Customer.setText(rs.getString("CustomerRenter"));
    }
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, e);
}
*/
     
    }//GEN-LAST:event_table3MouseClicked

    private void table3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_table3KeyReleased
          
     
    }//GEN-LAST:event_table3KeyReleased

    private void JJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JJActionPerformed

    private void ManuYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManuYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ManuYearActionPerformed

    private void AddCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCarActionPerformed
          try{
            if (IDCar.getText().length() > 5) {
        JOptionPane.showMessageDialog(null, "Error. Car ID must be maximum 5 characters long");
        return; 
            }
            
            //"
               String sql = "INSERT INTO Car3  VALUES(?,?,?,?,?,?,?,?,?,?); "; 
String sql2 =  MM.getSelectedItem().toString();
            pst = con.prepareStatement(sql);
            pst.setString(1,IDCar.getText());
            pst.setString(2,Type.getText());
            pst.setString(3,Brand.getText());
            pst.setString(4,Model.getText());
            pst.setString(5,ManuYear.getText());
            pst.setString(6,Color.getText());         
            pst.setString(7, LicensePlate.getText());
            pst.setString(8, sql2);
            pst.setString(9, HourlyRate.getText());
            pst.setString(10,Customer.getText());
            pst.execute();
            UpdateTable();
             System.out.println("Registration Successfull");
             JOptionPane.showMessageDialog(null, "Car Successfully Added");
 }
 catch(Exception e){
     System.out.println("Registration UnSuccessfull" + e);
             JOptionPane.showMessageDialog(null, "Error. CarID Belongs to Another Car");
 }
  finally{
            try{
            rs.close();
            pst.close();
            
        }
            catch(Exception e){
                
            }
        }
      
    }//GEN-LAST:event_AddCarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int row = table3.getSelectedRow();
        String cell = table3.getModel().getValueAt(row, 0).toString();
        String sql = "DELETE FROM Car3 WHERE ID = " + cell;
        try {
              pst = con.prepareStatement(sql);
             pst.execute();
           UpdateTable();
             JOptionPane.showMessageDialog(null, "Car Deleted ");
                
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        finally{
            try{
            rs.close();
            pst.close();
            
        }
            catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateCar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCar;
    private javax.swing.JTextField Brand;
    private javax.swing.JTextField Color;
    private javax.swing.JTextField Customer;
    private javax.swing.JTextField HourlyRate;
    private javax.swing.JTextField IDCar;
    private javax.swing.JComboBox<String> JJ;
    private javax.swing.JTextField LicensePlate;
    private javax.swing.JComboBox<String> MM;
    private javax.swing.JTextField ManuYear;
    private javax.swing.JTextField Model;
    private javax.swing.JTextField Type;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table3;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
